apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: practice-k8
spec:
  selector:
    app: my-nginx-app
  ports:
    - port: 81
      targetPort: 80
  type: ClusterIP

  # ClusterIP - gives ip of cluster (default) (expose service internally for other pods in cluster only, not to user....will need port-forward which act as temp. tunnel to connect to user)
  # NodePort - give the port for a node 30k-32k range (expose Node IP's for external access...we can access locally without port-forward)
  # loadbalancer - for cloud LB


# --------------------------------------------------------------------------------------
# If using type:NodePort, access the service using <NodeIP>:<NodePort>

# spec:
#   type: NodePort
#   selector:
#     app: frontend
#   ports:
#     - port: 80
#       targetPort: 80
#       nodePort: 30001

# >> kubectl get nodes -o wide or minikube ip ( to get NodeIP <- internal one for minikube)

# But it will not work as dockerdesktop run on WSL2 backend so we need to use command below
# minikube service <service-name> -n <namespace>
# it will createa a tunnel and open the service in browser