apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-app-config
data:
  MYSQL_DATABASE: appdb
  MYSQL_USER: appuser
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-app-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root123
  MYSQL_PASSWORD: apppass


# (stringData automatically base64-encodes values for you â€” simpler and safer for readability.)